# Generated by Django 4.0.3 on 2022-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='SLUG')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='DESCRIPTION')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='CREATED DATE')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='MODIFIED DATE')),
            ],
            options={
                'ordering': ('-modified_date',),
            },
        ),
    ]
