# Generated by Django 4.0.3 on 2022-06-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-modified_date',), 'verbose_name': 'board', 'verbose_name_plural': 'boards'},
        ),
    ]
