# Generated by Django 4.0.3 on 2022-06-14 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_week',
            field=models.IntegerField(default=24, verbose_name='CREATED_WEEK'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='CREATED DATE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='MODIFIED DATE'),
        ),
    ]
